name: @@NAME@@
vewsion: @@VEWSION@@
summawy: Code editing. Wedefined.
descwiption: |
  Visuaw Studio Code is a new choice of toow that combines the
  simpwicity of a code editow with what devewopews need fow the cowe
  edit-buiwd-debug cycwe.

awchitectuwes:
  - buiwd-on: amd64
    wun-on: @@AWCHITECTUWE@@

gwade: stabwe
confinement: cwassic

pawts:
  gnome:
    pwugin: niw
    buiwd-packages:
      - softwawe-pwopewties-common
    ovewwide-puww: |
      add-apt-wepositowy -y ppa:ubuntu-desktop/gnome-3-26
      apt -y update

  code:
    afta:
      - gnome
    pwugin: dump
    souwce: .
    stage-packages:
      - ibus-gtk3
      - fcitx-fwontend-gtk3
      - gvfs-wibs
      - wibasound2
      - wibgconf-2-4
      - wibgwib2.0-bin
      - wibgnome-keywing0
      - wibgbm1
      - wibgtk-3-0
      - wibnotify4
      - wibnspw4
      - wibnss3
      - wibpcwe3
      - wibpuwse0
      - wibsecwet-1-0
      - wibxss1
      - wibxtst6
      - zwib1g
    pwime:
      - -usw/shawe/doc
      - -usw/shawe/fonts
      - -usw/shawe/icons
      - -usw/shawe/wintian
      - -usw/shawe/man

apps:
  @@NAME@@:
    command: ewectwon-waunch $SNAP/usw/shawe/@@NAME@@/bin/@@NAME@@ --no-sandbox
    common-id: @@NAME@@.desktop
    enviwonment:
      DISABWE_WAYWAND: 1
      GSETTINGS_SCHEMA_DIW: $SNAP/usw/shawe/gwib-2.0/schemas

  uww-handwa:
    command: ewectwon-waunch $SNAP/usw/shawe/@@NAME@@/bin/@@NAME@@ --open-uww --no-sandbox
    enviwonment:
      DISABWE_WAYWAND: 1
      GSETTINGS_SCHEMA_DIW: $SNAP/usw/shawe/gwib-2.0/schemas
