{
    perform: true,
    alwaysRequireAssignee: false,
    labelsRequiringAssignee: [ feature-request ],
    autoAssignees: {
        api: [],
        color-picker: [],
        css-less-sass: [],
        debug: [ weinand ],
        diff-editor: [],
        editor: [],
        editor-1000-limit: [],
        editor-autoclosing: [],
        editor-autoindent: [],
        editor-brackets: [],
        editor-clipboard: [],
        editor-columnselect: [],
        editor-contrib: [],
        editor-core: [],
        editor-find-widget: [],
        editor-folding: [],
        editor-ime: [],
        editor-input: [],
        editor-minimap: [],
        editor-multicursor: [],
        editor-smooth: [],
        editor-wrapping: [],
        emmet: [ ramya-rao-a ],
        error-list: [],
        extensions: [],
        file-encoding: [],
        file-explorer: [],
        format: [],
        git: [ joaomoreno ],
        hot-exit: [ Tyriar ],
        html: [ aeschli ],
        i18n: [],
        install-update: [],
        integrated-terminal: [ Tyriar ],
        javascript: [ mjbvz ],
        json: [],
        keybindings: [],
        keyboard-layout: [],
        languages basic: [],
        markdown: [ mjbvz ],
        merge-conflict: [ chrmarti ],
        perf-profile: [],
        php: [ roblourens ],
        proxy: [],
        scm: [],
        search: [ roblourens ],
        snippets: [ jrieken ],
        tasks: [ dbaeumer ],
        telemetry: [],
        themes: [],
        typescript: [ mjbvz ],
        workbench: [ bpasero ],
        workbench-dnd: [],
        workbench-editors: [],
        workbench-feedback: [],
        workbench-layout: [],
        workbench-menu: [],
        workbench-notifications: [],
        workbench-state: [],
        workbench-status: [],
        workbench-tabs: [],
        workbench-welcome: [],
    }
}
