sudo: false
language: cpp
os:
- linux
- osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - gcc-4.9-multilib
    - g++-4.9-multilib
    - zip
    - libgtk2.0-0
env:
  global:
    secure: ZyBX/fw4MKGq88K/tTCt8/RGCihxWB0QnxFICUw3+uXulCARGq4G9bvVkxw4YZwD0CSbV9UedEy67VaNlGfuhYcJHaFm231n5yNm7+9pTpNaFlu25zwIXM3ELg4/QHiCDOZhsF91EdCrss/e8XnAZUjYWuq6NpAdolwPRtb/MD+PSQGivz7u4QUP229xESJYClkYyNpubJ9Yckg76JFWaLOxPtv6pGhRhhj93nUp6Tw8w8v/Q3JABUUhCWvZmfw/ZH8nYjAxlXqPJTmOeIVCyCCo0BoHYjGe3MsLNxzXq0swLRHbMUuAdRcraGRCXrOM6OEldI7nrpap+3xFKTjIQywdoWQNld5I9gBz6Z8JnH/YO+t46lKtboDD3Racry5nTTT6r+VobcIJatvDHWMuDl4QFPSF2AfACHsPByWtN59e/QqEmie8W7aMlOa2xuQvghKvugYnvwQx33d4EqchTwk7OUjjhCzhkr/BG+VRbEEKT6AWKTP+I0GeEfTdnTGVY+Frbq5Bo66enD+jTYhitPNOIGg1JVfd9XAaJFKh9EuY+X5E9wyJ1LQvS3If+d5EcC2+uJ1UnnMymL5nZCg9AmzpAE1lrkuV1wlcvLnuptQqRlfuhX9XFCLHFBv+1Ztu2zJ3lQLaK4eWJwLYADdbXrCwblUjlcoT9O0afcB0k6U=
  matrix:
  - USE_NETWORK=true
  - USE_NETWORK=false
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  github_token: d92bba44198832c75cf36652149f44eeae2d95fc
  keep_history: true
  on:
    branch: master
before_install:
- git submodule update --init --recursive
- git clone https://github.com/creationix/nvm.git ./.nvm
- source ./.nvm/nvm.sh
- brew install yarn
- brew install node@10
- echo 'export PATH="/usr/local/opt/node@10/bin:$PATH"' >> ~/.bash_profile
- echo 'export LDFLAGS="-L/usr/local/opt/node@10/lib"' >> ~/.bash_profile
- echo 'export CPPFLAGS="-I/usr/local/opt/node@10/include"' >> ~/.bash_profile
- echo 'alias node='node@10'' >> ~/.bash_profile
- echo 'export GITHUB_TOKEN='d92bba44198832c75cf36652149f44eeae2d95fc'' >> ~/.bash_profile
- source ~/.bash_profile
- npm update -g npm
- npm config set python `which python`
- npm install -g gulp
- if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
- "./scripts/npm.sh install --ignore-optional"
script:
- gulp hygiene
- gulp electron
- gulp compile
- chmod +x scripts/test.sh
- "./scripts/test.sh"
