sudo: false
language: cpp
os:
- linux
- osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - gcc-4.9-multilib
    - g++-4.9-multilib
    - zip
    - libgtk2.0-0
env:
  global:
    secure: qEDi4Hq/2UbbBSg7t7WlaJgfS2Wq0822p8Cq2UmxMR95S/q8ogYIhpPE8JDGqWSHCsLGuu56veIhn0qeBc62TyjFhDrx6VitwTvwgFlSBWJ1dQ80QhyZLevpa4NyeFKKxZPewIN2bSBsjR6635OxMOziJySEnr5rZeo8LTnkeJYGTux7BLYQYtxmkJJTW+DGU0h7dKyMITRQWXoicarMZ+mRi29fgkgnsa/YxUVuAxuZxsL77ZQ2kbFcv7jZdM1xmP1xVJBE6Tfhkqmt3RmHG2oNUuG4lkpmfNBBwr3tG5umAGs7LN2ptZ78JuDX7NrUZQznTNt5QIMU41f0wMEtq6Xit1g14RwWaApoLYpOAAHGfiiPuKYYBr5dyNEGejtsoIX2iMS+Ae36T24AB8ijOrashcArsbQGCCzUQXVp/ZKf+VDRseTutCtuie5BXvBWBPl7Rv/e0PAwtt7bBUswgkhnm8Okfllsqjgkvv5siK8UCDxWA499j2W2dY+iMw2MiGIdYqW86p97FWVhbAD8/1nD7JwpCHd5QWQZdhDS/72F0lJXFN2fpbtudnsB/RwQV30x+IqnD1SMFdQPIihN6BmEp0bPQukeH/YZwOOgm7gC1gXgPlW7FIEvUdctXjTzVuay+HrXO6lxtIAg4Ip9J0zC9yXld1+bYgDKv0kJ2JY=
  matrix:
  - USE_NETWORK=true
  - USE_NETWORK=false
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  github_token: d92bba44198832c75cf36652149f44eeae2d95fc
  keep_history: true
  on:
    branch: master
before_install:
- git submodule update --init --recursive
- git clone https://github.com/creationix/nvm.git ./.nvm
- source ./.nvm/nvm.sh
- brew install yarn
- brew install node@10
- echo 'export PATH="/usr/local/opt/node@10/bin:$PATH"' >> ~/.bash_profile
- echo 'export LDFLAGS="-L/usr/local/opt/node@10/lib"' >> ~/.bash_profile
- echo 'export CPPFLAGS="-I/usr/local/opt/node@10/include"' >> ~/.bash_profile
- echo 'alias node='node@10'' >> ~/.bash_profile
- echo 'export GITHUB_TOKEN='d92bba44198832c75cf36652149f44eeae2d95fc'' >> ~/.bash_profile
- source ~/.bash_profile
- npm update -g npm
- npm config set python `which python`
- npm install -g gulp
- if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
- "./scripts/npm.sh install --ignore-optional"
script:
- gulp hygiene
- gulp electron
- gulp compile
- chmod +x scripts/test.sh
- "./scripts/test.sh"
