sudo: false
language: node_js

os:
  - linux
  - osx
  - windows

cache:
  directories:
    - $HOME/.cache/yarn

notifications:
  email: false


before_install:
  - export GITHUB_TOKEN=$PUBLIC_GITHUB_TOKEN
  - git submodule update --init --recursive
  - nvm install 8.9.1
  - nvm use 8.9.1
  - npm i -g yarn

install:
  - yarn

script:
  - node_modules/.bin/gulp electron --silent
  - node_modules/.bin/gulp compile --silent --max_old_space_size=4096
  - ./scripts/test-integration.sh

matrix:
  include:
    - os: linux
      env: label=hygiene
      script: node_modules/.bin/gulp hygiene
      after_success: skip