blank_issues_enabled: false
contact_links:
  - name: Question & Suggestions
    url: https://github.com/Splizard/vscode-mobile/discussions
    about: Please ask and answer questions here.
  - name: Extension Development
    url: https://github.com/Splizard/vscode-mobile/discussions
    about: Please use this for mobile-specific extension development questions and ideas.
