name: Feature request
description: Suggest an idea for this project
title: "feat: "
labels: ["feature-request"]


body:
  - type: checkboxes
    id: reporter-agreement
    attributes:
      label: Reporter Agreement
      options:
        - label: Agreed to [Rules Of Conduct](https://opensource.microsoft.com/codeofconduct/)
          required: true
        - label: Not a Duplicate Issue!. 🔎 Search for existing issues over [here](https://github.com/microsoft/vscode/issues)
          required: true

  - type: textarea
    id: feature
    attributes:
      label: "Describe the feature"
      description: "explain the feature, usecases in detail"
    validations:
      required: true


