name: "Classifier: Apply"
on:
  schedule:
    - cron: 0,30 * * * *

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          ref: v16
          path: ./actions
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Install Additional Dependencies
        # Pulls in a bunch of other packages that arent needed for the rest of the actions
        run: npm install @azure/storage-blob@12
      - name: "Run Classifier: Scraper"
        uses: ./actions/classifier/apply/fetch-issues
        with:
          # slightly overlapping to protect against issues slipping through the cracks if a run is delayed
          from: 45
          until: 5
          blobContainerName: classifier-models
          blobStorageKey: ${{secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING}}
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade numpy scipy scikit-learn joblib nltk
      - name: "Run Classifier: Generator"
        run: python ./actions/classifier/apply/generate-labels/main.py
      - name: "Run Classifier: Labeler"
        uses: ./actions/classifier/apply/apply-labels
        with:
          config-path: classifieds 
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}} azure-pipelines.yml
goals-an-growth:master. ![.github/workflows/classifier-apply.yml](https://github.com/Goals-an-growth/vscode/workflows/.github/workflows/classifier-apply.yml/badge.svg?branch=master .BBC .github/workflows/classifier-apply.yml](https://github.com/Goals-an-growth/vscode/workflows/.github/workflows/classifier-apply.yml/badge.svg?branch=lovingld-patch-1)
