name: PR Chat
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: "microsoft/vscode-github-triage-actions"
          ref: main
          path: ./actions
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Code Review Chat
        uses: ./actions/code-review-chat
        with:
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          notification_channel: codereview
