name: "Rich Navigation Indexing"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  richnav:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: caching-stage
        name: Cache VS Code dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies-${{ hashfiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-dependencies-

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        if: steps.caching-stage.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
        env:
          CHILD_CONCURRENCY: 1

      - uses: brianaeng/RichCodeNavIndexer@v0.1
        with:
          environment: development
          languages: typescript
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          typescriptVersion: 0.6.0-next.19
          configFiles: .lsifrc.json
          nugetFeed: https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-buildservices/nuget/v3/index.json
        continue-on-error: true
